### ISSUE TITLE
Test failure in test_request__patch

### ISSUE THREAD

**Issue by felixonmars** [praw-dev/prawcore#53]
I am having the following error when running the test suites. Same errors are present in Python 2.7 and 3.5, too.

Other version info:
betamax-matchers 0.3.0
betamax-serializers 0.2.0
requests 2.12.4

```
======================================================================
ERROR: test_request__patch (tests.test_sessions.SessionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-prawcore/src/prawcore/prawcore/requestor.py", line 46, in request
    return self._http.request(*args, timeout=TIMEOUT, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/betamax/adapter.py", line 132, in send
    current_cassette))
betamax.exceptions.BetamaxError: A request was made that could not be handled.

A request was made to https://www.reddit.com/api/v1/access_token that could not be found in Session_request__patch.

The settings on the cassette are:

    - record_mode: once
    - match_options {'json-body', 'method', 'uri'}.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/python-prawcore/src/prawcore/tests/test_sessions.py", line 77, in test_request__patch
    session = prawcore.Session(script_authorizer())
  File "/build/python-prawcore/src/prawcore/tests/test_sessions.py", line 41, in script_authorizer
    authorizer.refresh()
  File "/build/python-prawcore/src/prawcore/prawcore/auth.py", line 328, in refresh
    password=self._password)
  File "/build/python-prawcore/src/prawcore/prawcore/auth.py", line 138, in _request_token
    response = self._authenticator._post(url, **data)
  File "/build/python-prawcore/src/prawcore/prawcore/auth.py", line 29, in _post
    data=sorted(data.items()))
  File "/build/python-prawcore/src/prawcore/prawcore/requestor.py", line 48, in request
    raise RequestException(exc, args, kwargs)
prawcore.exceptions.RequestException: error with request A request was made that could not be handled.

A request was made to https://www.reddit.com/api/v1/access_token that could not be found in Session_request__patch.

The settings on the cassette are:

    - record_mode: once
    - match_options {'json-body', 'method', 'uri'}.


----------------------------------------------------------------------
Ran 80 tests in 26.563s

FAILED (errors=1)
```

**Comment by bboe** [comment]
What is it that you're trying to do? How are you running the tests?

**Comment by felixonmars** [comment]
I am packaging prawcore for Arch Linux, and I use `python setup.py test` to run the tests in the source folder.

**Comment by bboe** [comment]
Part of the problem could be that your package requirements don't match up with the test package  requirements in `setup.py`:

```
tests_require=['betamax >=0.8, <0.9',
                     'betamax-matchers >=0.2.0, <0.3',
                     'betamax-serializers >=0.2, <0.3',
                     'mock ==1.0.1',
                     'pytest ==2.8.7'],
```

**Comment by bboe** [comment]
Is the 0.3.0 version of betamax matchers you have installed the one from the master branch as specified by the following that appears in `setup.py`?

```
      dependency_links=[
          ('https://github.com/sigmavirus24/betamax_matchers/tarball/master'
           '#egg=betamax_matchers-0.3.0')
      ],
```

**Comment by bboe** [comment]
Based on the fact that I could reproduce with the not correct version of betamax_matchers, I'm going to close this issue. I certainly would appreciate a confirmation if that's correct, or please reopen if that's not.

**Comment by felixonmars** [comment]
Thank you, and that's exactly the reason. Sorry for the false alarm!
